name: Build and deploy to Northflank

on:
  push:
    branches: ['master']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to Northflank
        uses: ./.github/actions/deploy-docker-image-action
        with:
          northflank-api-key: ${{ secrets.NORTHFLANK_API_KEY }}
          project-id: default-project
          service-id: gh-action-experiment
          image-path: nginx:latest